(custom-set-variables
 '(make-backup-files nil)
 '(vhdl-array-index-record-field-in-sensitivity-list nil)
 '(vhdl-compose-configuration-create-file t)
 '(vhdl-electric-mode nil)
 '(vhdl-end-comment-column 790)
 '(vhdl-entity-file-name (quote (".*" . "\\&-e")))
 '(vhdl-file-header "")
 '(vhdl-include-port-comments t)
 '(vhdl-inline-comment-column 840)
 '(vhdl-project nil)
'(vhdl-project-alist (quote (("projectname" "" "$PROJ_ROOT/" ("$PROJ_ROOT/rtl/") "" nil "./" "work" "work/" "" ""))))
 '(vhdl-prompt-for-comments nil)
;;'(vhdl-speedbar-auto-open t)
;; '(vhdl-speedbar-display-mode (quote project))
 '(vhdl-speedbar-scan-limit (quote (nil (nil nil)))))
